In [ ]:
import numpy as np

np.random.seed(0)

x = [
  [1, 2, 3, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]
]

class LayerDense:
  def __init__(self, num_inputs, num_neurons):
    self.weights = .1 * np.random.randn(num_inputs, num_neurons)
    self.biases = np.zeros((1, num_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = LayerDense(4, 5)
layer2 = LayerDense(5, 2)

layer1.forward(x)
layer2.forward(layer1.output)

print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
