In [19]:
import nnfs.datasets
import numpy as np
import nnfs

nnfs.init()

class LayerDense:
  def __init__(self, num_inputs, num_neurons):
    self.weights = .1 * np.random.randn(num_inputs, num_neurons)
    self.biases = np.zeros((1, num_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class ActivationReLU:
  def forward(self, inputs):  
    self.output = np.maximum(0, inputs)

class ActivationSoftmax:
  def __init__(self):
    self.output = None

  def forward(self, inputs):
    exponentiated = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exponentiated / np.sum(exponentiated, axis=1, keepdims=True)

    self.output = probabilities

x, y = nnfs.datasets.spiral_data(samples = 100, classes = 3)
dense1 = LayerDense(2, 3)
activation1 = ActivationReLU()
dense2 = LayerDense(3, 3)
activation2 = ActivationSoftmax()

dense1.forward(x)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
