In [ ]:
import nnfs.datasets
import numpy as np
import nnfs

nnfs.init()

class LayerDense:
  def __init__(self, num_inputs, num_neurons):
    self.weights = .1 * np.random.randn(num_inputs, num_neurons)
    self.biases = np.zeros((1, num_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class ActivationReLU:
  def forward(self, inputs):  
    self.output = np.maximum(0, inputs)

class ActivationSoftmax:
  def __init__(self):
    self.output = None

  def forward(self, inputs):
    exponentiated = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exponentiated / np.sum(exponentiated, axis=1, keepdims=True)

    self.output = probabilities

x, y = nnfs.datasets.spiral_data(samples = 100, classes = 3)
dense1 = LayerDense(2, 3)
activation1 = ActivationReLU()
dense2 = LayerDense(3, 3)
activation2 = ActivationSoftmax()

dense1.forward(x)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]
 [0.33328417 0.33328718 0.33342862]
 [0.33318216 0.33319145 0.33362636]
 [0.33318278 0.33319202 0.33362517]
 [0.33314922 0.33316055 0.3336902 ]
 [0.3331059  0.33311984 0.3337743 ]
 [0.3330813  0.3330968  0.33382186]
 [0.33311027 0.33312503 0.33376473]
 [0.3330537  0.33307084 0.33387548]
 [0.33300948 0.33302936 0.3339612 ]
 [0.33301342 0.33303303 0.33395353]
 [0.33299845 0.333019   0.3339825 ]
 [0.33312678 0.33318865 0.3336846 ]
 [0.3329409  0.33296496 0.33409408]
 [0.33299428 0.33303145 0.33397427]
 [0.3328737  0.33290187 0.33422446]
 [0.3328757  0.33290377 0.33422053]
 [0.33309552 0.33318356 0.33372095]
 [0.33317605 0.33328283 0.3335411 ]
 [0.332894   0.33293876 0.33416727]
 [0.3325638  0.33270204 0.3347342 ]
 [0.33281362 0.33284548 0.3343409 ]
 [0.33314455 0.33327034 0.33358508]
 [0.3331285  0.333258   0.33