In [ ]:
import numpy as np
import nnfs

nnfs.init()

from nnfs.datasets import spiral_data

class LayerDense:
  def __init__(self, num_inputs, num_neurons):
    self.weights = .1 * np.random.randn(num_inputs, num_neurons)
    self.biases = np.zeros((1, num_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class ActivationReLU:
  def forward(self, inputs):  
    self.output = np.maximum(0, inputs)

x, y = spiral_data(samples=100, classes=2)

layer1 = LayerDense(2, 5)
activation1 = ActivationReLU()

layer1.forward(x)
activation1.forward(layer1.output)


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00]
 [-1.6704046e-03 -9.5173855e-05 -3.8254017e-04  4.6632026e-04
   9.7073214e-05]
 [-2.9919860e-03 -3.4620197e-04  2.6788190e-04  1.2796856e-03
   6.7180151e-04]
 [-1.8258524e-03 -7.2835456e-04  2.9679232e-03  2.0886525e-03
   1.8751227e-03]
 [-2.9596870e-03 -9.6375053e-04  3.6345762e-03  2.8371245e-03
   2.4249570e-03]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.6632026e-04 9.7073214e-05]
 [0.0000000e+00 0.0000000e+00 2.6788190e-04 1.2796856e-03 6.7180151e-04]
 [0.0000000e+00 0.0000000e+00 2.9679232e-03 2.0886525e-03 1.8751227e-03]
 [0.0000000e+00 0.0000000e+00 3.6345762e-03 2.8371245e-03 2.4249570e-03]]
